### ISSUE TITLE
ие11: не помещаются заголовки при ресайзе

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-dokspb2#100]
http://prntscr.com/l1a0px до 520рх
http://prntscr.com/l1a1sw
http://prntscr.com/l1a1wy
так же в верхней форме поправить значек выпадающего списка: http://prntscr.com/l1a2gq

**Comment by VladyslavKovalchuk** [comment]
ломаются картинки в этом слайдере http://prntscr.com/l2lg9u

**Comment by Derevyanchenko** [comment]
это относится к другой правке же
