### ISSUE TITLE
перепроверить pagespeed, html валидатор

### ISSUE THREAD

**Issue by VladyslavKovalchuk** [nicolaypetrovich/rocket-dokspb2#83]
http://prntscr.com/l18czx
http://prntscr.com/l18dbq
по html проверить все страницы, минимум по 4 ошибки на странице
в pagespeed можно еще оптимизировать

**Comment by Derevyanchenko** [comment]
поправил все, только на страницах вопросы и отзывы остались по одной ошибке вордпресса(их Макс пофиксит)

**Comment by VladyslavKovalchuk** [comment]
на главной в валидаторе одна ошибка осталась http://prntscr.com/l3w18g

**Comment by Derevyanchenko** [comment]
это не в верстке пробема, это видею с ютуба(которое загружается с админки)
